# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""
Type annotations for transformagenticservice service literal definitions.

[Open documentation](https://youtype.github.io/boto3_stubs_docs/agent_builder_types/literals/)

Usage::

    ```python
    from agent_builder_types.literals import AccessControlType

    data: AccessControlType = "DISABLED"
    ```
"""

import sys

if sys.version_info >= (3, 12):
    from typing import Literal
else:
    from typing_extensions import Literal

__all__ = (
    "AccessControlType",
    "AccountConnectionStatusType",
    "ActionType",
    "AgentConfigurationAvailabilityType",
    "AgentInstanceStatusType",
    "AgentTypeType",
    "AgentVisibilityType",
    "BlockingTypeType",
    "CategoryType",
    "CategoryTypeType",
    "ChunkingStrategyType",
    "ClosureTypeType",
    "CopyStatusType",
    "FailureCategoryType",
    "FileTypeType",
    "HitlTaskStatusType",
    "HitlTaskTypeType",
    "IngestionStatusType",
    "JobStatusType",
    "KnowledgeBaseConfigTypeType",
    "ListAgentInstancesPaginatorName",
    "ListArtifactsPaginatorName",
    "ListHitlTasksPaginatorName",
    "ListJobPlanStepsPaginatorName",
    "MeteredUnitType",
    "MonitoringTypeType",
    "OwnerTypeType",
    "PlanStepStatusType",
    "PutJobPlanStatusType",
    "ResourceTypeType",
    "RetrievalResultLocationTypeType",
    "RetrievalScopeType",
    "SeverityType",
    "UmrAgreementStatusType",
    "UmrEligibilityOutcomeType",
    "UmrIncentiveTypeType",
    "UmrMigrationPhaseType",
    "UmrPartnerTypeType",
    "UmrResourceStatusType",
    "UmrResourceTypeType",
    "UmrRiskLevelType",
    "UmrStatusType",
    "UpdateAgentInstanceStatusType",
    "VersionStatusType",
    "VisibilityType",
    "TransformAgenticServiceServiceName",
    "ServiceName",
    "ResourceServiceName",
    "PaginatorName",
)

AccessControlType = Literal["DISABLED", "ENABLED"]
AccountConnectionStatusType = Literal["ACTIVE", "PENDING", "REJECTED"]
ActionType = Literal["APPROVE", "REJECT"]
AgentConfigurationAvailabilityType = Literal[
    "ANY", "NEEDS_RUNTIME_CONFIGURATION", "RUNTIME_CONFIGURATION_AVAILABLE"
]
AgentInstanceStatusType = Literal[
    "COMPLETED", "FAILED", "INVOKED", "INVOKING", "RUNNING", "STOPPED", "STOPPING", "UNRESPONSIVE"
]
AgentTypeType = Literal["ORCHESTRATOR_AGENT", "SUB_AGENT"]
AgentVisibilityType = Literal["PUBLIC", "RESTRICTED"]
BlockingTypeType = Literal["BLOCKING", "NON_BLOCKING"]
CategoryType = Literal["REGULAR", "TOOL_APPROVAL"]
CategoryTypeType = Literal[
    "AGENT_INPUT",
    "AGENT_OUTPUT",
    "CUSTOMER_INPUT",
    "CUSTOMER_OUTPUT",
    "HITL_FROM_AGENT",
    "HITL_FROM_USER",
    "INTERNAL",
    "PLAN_STEP_OUTPUT",
    "PLAN_STEP_SUMMARY",
    "STATE",
]
ChunkingStrategyType = Literal["FIXED_SIZE", "HIERARCHICAL", "NONE", "SEMANTIC"]
ClosureTypeType = Literal["CANCELLED", "CLOSED", "CLOSED_PENDING_NEXT_TASK"]
CopyStatusType = Literal["COMPLETED", "IN_PROGRESS"]
FailureCategoryType = Literal["CUSTOMER_ERROR", "EXPECTED_FAILURE", "SERVICE_ERROR"]
FileTypeType = Literal[
    "CSV", "HTML", "JSON", "MARKDOWN", "OTHER", "PDF", "PPTX", "TXT", "XLSX", "ZIP"
]
HitlTaskStatusType = Literal[
    "AWAITING_APPROVAL",
    "AWAITING_HUMAN_INPUT",
    "CANCELLED",
    "CLOSED",
    "CLOSED_PENDING_NEXT_TASK",
    "CREATED",
    "DELIVERED",
    "IN_PROGRESS",
    "SUBMITTED",
    "WAITING_APPROVAL",
]
HitlTaskTypeType = Literal["DASHBOARD", "NORMAL"]
IngestionStatusType = Literal[
    "COMPLETE", "FAILED", "IN_PROGRESS", "STARTING", "STOPPED", "STOPPING"
]
JobStatusType = Literal[
    "ASSESSING",
    "AWAITING_HUMAN_INPUT",
    "COMPLETED",
    "CREATED",
    "EXECUTING",
    "FAILED",
    "PLANNED",
    "PLANNING",
    "STARTING",
    "STOPPED",
    "STOPPING",
]
KnowledgeBaseConfigTypeType = Literal["TEXT_TITAN_CONFIG"]
ListAgentInstancesPaginatorName = Literal["list_agent_instances"]
ListArtifactsPaginatorName = Literal["list_artifacts"]
ListHitlTasksPaginatorName = Literal["list_hitl_tasks"]
ListJobPlanStepsPaginatorName = Literal["list_job_plan_steps"]
MeteredUnitType = Literal["COUNT"]
MonitoringTypeType = Literal["HEALTHCHECK", "HEARTBEAT"]
OwnerTypeType = Literal["DIRECT_AGENT", "INTERNAL_AGENT", "MARKETPLACE_AGENT"]
PlanStepStatusType = Literal[
    "FAILED", "IN_PROGRESS", "NOT_STARTED", "PENDING_HUMAN_INPUT", "STOPPED", "SUCCEEDED"
]
PutJobPlanStatusType = Literal["COMPLETED", "IN_PROGRESS"]
ResourceTypeType = Literal[
    "ASSESSMENTS_MONTHLY_COMPLETED_ASSESSMENTS",
    "DOT_NET_TRANSFORMATION_BILLED_LOC",
    "DOT_NET_TRANSFORMATION_MONTHLY_LOC",
    "DOT_NET_TRANSFORMATION_MONTHLY_REPOSITORIES",
    "DOT_NET_TRANSFORMATION_TOTAL_LOC",
    "MAINFRAME_ANALYSIS_LOC",
    "MAINFRAME_ASSESSMENT_LOC",
    "MAINFRAME_BUSINESS_RULE_DEPENDENCY_LOC",
    "MAINFRAME_BUSINESS_RULE_LOC",
    "MAINFRAME_DATA_ANALYSIS_LOC",
    "MAINFRAME_DECOMPOSITION_LOC",
    "MAINFRAME_DOCUMENTATION_DEPENDENCY_LOC",
    "MAINFRAME_DOCUMENTATION_LOC",
    "MAINFRAME_LOC",
    "MAINFRAME_PLAN_MIGRATION_ITERATION",
    "MAINFRAME_REFORGE_LOC",
    "MAINFRAME_TESTPLAN_LLM_CALLS",
    "MAINFRAME_TESTPLAN_LOC",
    "MAINFRAME_TESTPLAN_TC_APPROVED",
    "MAINFRAME_TESTPLAN_TC_GENERATED",
    "MAINFRAME_TESTPLAN_TC_GUIDANCE",
    "MAINFRAME_TEST_DATA_COLLECTION_TC_SELECTED",
    "MAINFRAME_TEST_SCRIPT_GENERATION_TC_SELECTED",
    "MAINFRAME_TRANSFORM_LOC",
    "QT_AGENTIC_PLATFORM_BILLING_TEST",
    "QT_AGENTIC_PLATFORM_TEST",
    "VMS_MIGRATED_SUCCESSFUL_COUNT",
    "VM_NETWORKS_DEPLOYED_COUNT",
    "VM_NETWORKS_GENERATED_COUNT",
]
RetrievalResultLocationTypeType = Literal["S3", "WEB"]
RetrievalScopeType = Literal["AGENT_INGESTED", "AWS", "PRODUCT"]
SeverityType = Literal["CRITICAL", "STANDARD"]
UmrAgreementStatusType = Literal["AMENDED", "EXECUTED", "PENDING", "TERMINATED"]
UmrEligibilityOutcomeType = Literal["APPROVED", "DENIED", "PENDING"]
UmrIncentiveTypeType = Literal["CASH", "CASH_AND_CREDIT", "CREDIT"]
UmrMigrationPhaseType = Literal["ASSESS", "MIGRATE", "MOBILIZE", "MODERNIZE"]
UmrPartnerTypeType = Literal[
    "CONSULTING_PARTNER",
    "DISTRIBUTOR",
    "MANAGED_SERVICE_PROVIDER",
    "SOLUTION_PROVIDER",
    "SYSTEM_INTEGRATOR",
]
UmrResourceStatusType = Literal["APPROVED", "DENIED", "PENDING", "SUBMITTED"]
UmrResourceTypeType = Literal[
    "BENEFIT_ALLOCATION",
    "BENEFIT_APPLICATION",
    "MIGRATION_ENGAGEMENT_RECORD",
    "OPPORTUNITY",
    "OTHER",
]
UmrRiskLevelType = Literal["HIGH", "LOW", "MEDIUM"]
UmrStatusType = Literal["ACTIVE", "CANCELLED", "COMPLETED"]
UpdateAgentInstanceStatusType = Literal["COMPLETED", "FAILED", "RUNNING", "STOPPED"]
VersionStatusType = Literal["ACTIVE", "CREATED", "IN_VERIFICATION", "VERIFICATION_FAILED"]
VisibilityType = Literal["EXTERNAL", "INTERNAL"]
TransformAgenticServiceServiceName = Literal["transformagenticservice"]
ServiceName = Literal[
    "accessanalyzer",
    "account",
    "acm",
    "acm-pca",
    "aiops",
    "amp",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "apigateway",
    "apigatewaymanagementapi",
    "apigatewayv2",
    "appconfig",
    "appconfigdata",
    "appfabric",
    "appflow",
    "appintegrations",
    "application-autoscaling",
    "application-insights",
    "application-signals",
    "applicationcostprofiler",
    "appmesh",
    "apprunner",
    "appstream",
    "appsync",
    "apptest",
    "arc-region-switch",
    "arc-zonal-shift",
    "artifact",
    "athena",
    "atx-agent-registry-ext",
    "atx-agent-registry-int",
    "atxagentregistryexternal",
    "auditmanager",
    "authz",
    "autoscaling",
    "autoscaling-plans",
    "awstransformagenticservice",
    "awstransformagentregistryexternal",
    "b2bi",
    "backup",
    "backup-gateway",
    "backupsearch",
    "batch",
    "bcm-dashboards",
    "bcm-data-exports",
    "bcm-pricing-calculator",
    "bcm-recommended-actions",
    "bedrock",
    "bedrock-agent",
    "bedrock-agent-runtime",
    "bedrock-agentcore",
    "bedrock-agentcore-control",
    "bedrock-data-automation",
    "bedrock-data-automation-runtime",
    "bedrock-runtime",
    "billing",
    "billingconductor",
    "braket",
    "budgets",
    "ce",
    "chat",
    "chatbot",
    "chime",
    "chime-sdk-identity",
    "chime-sdk-media-pipelines",
    "chime-sdk-meetings",
    "chime-sdk-messaging",
    "chime-sdk-voice",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudcontrol",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudfront-keyvaluestore",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudsearchdomain",
    "cloudtrail",
    "cloudtrail-data",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguru-reviewer",
    "codeguru-security",
    "codeguruprofiler",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "config",
    "connect",
    "connect-contact-lens",
    "connectcampaigns",
    "connectcampaignsv2",
    "connectcases",
    "connectparticipant",
    "consolas",
    "controlcatalog",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "customer-profiles",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devicefarm",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "docdb-elastic",
    "drs",
    "ds",
    "ds-data",
    "dsql",
    "dynamodb",
    "dynamodbstreams",
    "ebs",
    "ec2",
    "ec2-instance-connect",
    "ecr",
    "ecr-public",
    "ecs",
    "efs",
    "egartifact",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elasticgumbyagenticservice",
    "elastictranscoder",
    "elb",
    "elbv2",
    "emr",
    "emr-containers",
    "emr-serverless",
    "entityresolution",
    "es",
    "events",
    "evidently",
    "evs",
    "external-registry",
    "finspace",
    "finspace-data",
    "firehose",
    "fis",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "freetier",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo-maps",
    "geo-places",
    "geo-routes",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "identitystore",
    "imagebuilder",
    "importexport",
    "inspector",
    "inspector-scan",
    "inspector2",
    "internetmonitor",
    "invoicing",
    "iot",
    "iot-data",
    "iot-jobs-data",
    "iot-managed-integrations",
    "iotanalytics",
    "iotdeviceadvisor",
    "iotevents",
    "iotevents-data",
    "iotfleethub",
    "iotfleetwise",
    "iotsecuretunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivs-realtime",
    "ivschat",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "keyspaces",
    "keyspacesstreams",
    "kinesis",
    "kinesis-video-archived-media",
    "kinesis-video-media",
    "kinesis-video-signaling",
    "kinesis-video-webrtc-storage",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "launch-wizard",
    "lex-models",
    "lex-runtime",
    "lexv2-models",
    "lexv2-runtime",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "lookoutmetrics",
    "lookoutvision",
    "m2",
    "machinelearning",
    "macie2",
    "mailmanager",
    "managedblockchain",
    "managedblockchain-query",
    "marketplace-agreement",
    "marketplace-catalog",
    "marketplace-deployment",
    "marketplace-entitlement",
    "marketplace-reporting",
    "marketplacecommerceanalytics",
    "mde",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "mediastore-data",
    "mediatailor",
    "medical-imaging",
    "memorydb",
    "meteringmarketplace",
    "mgh",
    "mgn",
    "migration-hub-refactor-spaces",
    "migrationhub-config",
    "migrationhuborchestrator",
    "migrationhubstrategy",
    "mpa",
    "mq",
    "mturk",
    "mwaa",
    "neptune",
    "neptune-graph",
    "neptunedata",
    "network-firewall",
    "networkflowmonitor",
    "networkmanager",
    "networkmonitor",
    "notifications",
    "notificationscontacts",
    "oam",
    "observabilityadmin",
    "odb",
    "om",
    "omics",
    "opensearch",
    "opensearchserverless",
    "opsworks",
    "opsworkscm",
    "orchestration",
    "organizations",
    "osis",
    "outposts",
    "panorama",
    "partnercentral-selling",
    "payment-cryptography",
    "payment-cryptography-data",
    "pca-connector-ad",
    "pca-connector-scep",
    "pcs",
    "personalize",
    "personalize-events",
    "personalize-runtime",
    "pi",
    "pinpoint",
    "pinpoint-email",
    "pinpoint-sms-voice",
    "pinpoint-sms-voice-v2",
    "pipes",
    "polly",
    "pricing",
    "proton",
    "qapps",
    "qbusiness",
    "qconnect",
    "qldb",
    "qldb-session",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-data",
    "redshift-serverless",
    "rekognition",
    "repostspace",
    "resiliencehub",
    "resource-explorer-2",
    "resource-groups",
    "resourcegroupstaggingapi",
    "robomaker",
    "rolesanywhere",
    "route53",
    "route53-recovery-cluster",
    "route53-recovery-control-config",
    "route53-recovery-readiness",
    "route53domains",
    "route53profiles",
    "route53resolver",
    "rum",
    "s3",
    "s3control",
    "s3outposts",
    "s3tables",
    "s3vectors",
    "sagemaker",
    "sagemaker-a2i-runtime",
    "sagemaker-edge",
    "sagemaker-featurestore-runtime",
    "sagemaker-geospatial",
    "sagemaker-metrics",
    "sagemaker-runtime",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "security-ir",
    "securityhub",
    "securitylake",
    "segst",
    "segst-as",
    "segst-cl",
    "serverlessrepo",
    "service-quotas",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "ses",
    "sesv2",
    "shield",
    "signer",
    "simspaceweaver",
    "sms",
    "sms-voice",
    "snow-device-management",
    "snowball",
    "sns",
    "socialmessaging",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-guiconnect",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "sso-admin",
    "sso-oidc",
    "stepfunctions",
    "storagegateway",
    "sts",
    "supplychain",
    "support",
    "support-app",
    "swf",
    "synthetics",
    "taxsettings",
    "tcpexternal",
    "textract",
    "timestream-influxdb",
    "timestream-query",
    "timestream-write",
    "tnb",
    "transcribe",
    "transfer",
    "transformagenticservice",
    "translate",
    "trustedadvisor",
    "verifiedpermissions",
    "voice-id",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wisdom",
    "workdocs",
    "workmail",
    "workmailmessageflow",
    "workspaces",
    "workspaces-instances",
    "workspaces-thin-client",
    "workspaces-web",
    "xray",
]
ResourceServiceName = Literal[
    "cloudformation",
    "cloudwatch",
    "dynamodb",
    "ec2",
    "glacier",
    "iam",
    "opsworks",
    "s3",
    "sns",
    "sqs",
]
PaginatorName = Literal[
    "list_agent_instances", "list_artifacts", "list_hitl_tasks", "list_job_plan_steps"
]
